### ISSUE TITLE
How do you merge the EAP repo with the local maven repository? 

### ISSUE THREAD

**Issue by raghav01ib** [EAT-JBCOMMUNITY/EAT#130]

**Comment by EAT-JBCOMMUNITY** [comment]
For any server you should have/download the artifacts used by the server, either by building the server, or by having the server artifacts in the local repo. In any case the parent pom of the server version that you test is needed so that the equivalent artifact versions are used by EAT ...

**Comment by raghav01ib** [comment]
Thank you! the wildfly versions did contain the pom and are working fine, the issue was just with the EAP, for which I had to create a pom, and is now running well with EAT, Thanks !!
